import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Kosugi_Maru } from "next/font/google"; // 追加

const kosugi = Kosugi_Maru({
  weight: "400", 
  subsets: ["latin"], 
  variable: "--font-kosugi-maru", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body className={kosugi.className}>
        {children}
      </body>
    </html>
  );
}