-- Modify nyuyoku_log table schema: change user_id from PK to FK, add auto-increment id as PK
-- This allows multiple bath logs per user

-- Drop existing primary key constraint
ALTER TABLE "public"."nyuyoku_log" DROP CONSTRAINT "nyuyoku_log_pkey";

-- Add new auto-increment id column as primary key
ALTER TABLE "public"."nyuyoku_log" 
ADD COLUMN "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;

-- Add foreign key constraint to user_id referencing auth.users
ALTER TABLE "public"."nyuyoku_log" 
ADD CONSTRAINT "nyuyoku_log_user_id_fkey" 
FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Add index on user_id for better query performance
CREATE INDEX "nyuyoku_log_user_id_idx" ON "public"."nyuyoku_log"("user_id");

-- Add index on created_at for time-based queries
CREATE INDEX "nyuyoku_log_created_at_idx" ON "public"."nyuyoku_log"("created_at");

COMMENT ON COLUMN "public"."nyuyoku_log"."id" IS 'Auto-increment primary key for each bath log entry';
COMMENT ON COLUMN "public"."nyuyoku_log"."user_id" IS 'Foreign key reference to auth.users, allows multiple bath logs per user';
